### ISSUE TITLE
OffsetStrategy.SYNC commits even with exception

### ISSUE THREAD

**Issue by rabend** [micronaut-projects/micronaut-kafka#39] opened 2019-06-07 12:46 UTC
The documentation for OffsetStrategy.SYNC states: 

> Commits offsets manually at the end of each poll() loop if no exceptions occur.

The scenario is the following:
My consumer receives two messages in the same poll loop, A and B.
A comes in first and cannot be processed, an Exception is thrown.
B comes in second, gets processed successfully.
B's offset gets committed, automatically committing A's offset too.

From the documentation I would have expected that neither A's nor B's offset get committed, because of the exception raised by A's processing.

If my understanding of this is incorrect please tell me, I'm happy to improve my knowledge about this. Otherwise I can supply a minimum working example to show what I mean

**Comment by graemerocher** [comment] 2019-06-07 12:48
Please provide an example that reproduces the issue

**Comment by rabend** [comment] 2019-06-07 12:55
https://github.com/rabend/micronaut-kafka-issue-39

Please start the docker containers, then run gradle build. The test should be green, as no offsets should have been committed.

**Comment by graemerocher** [comment] 2019-06-07 12:56
Thanks we will take a look

**Comment by kziomek** [comment] 2019-06-14 15:46
We have the same issue. 
Micronaut indeed do not commit offset on error when **SYNC strategy** is used. Unfortunately next successful message will cause offset to be committed.

**Our processing requirements:**
In our system each message has to be processed at least once. 
We need to call external services to process our message. They might not be available at processing time so we need to retry calling them later.
We are retrying http call 2 times before throwing exception to KafkaListener.

**Initial, not working solution**
Initially we configured our KafkaListener to be invoked with single message by Micronaut framework. We noticed that Micronaute don't try to reprocess failed messages. It simply log an error and call our KafkaListener with next message which couse offset to be commited when processed successfuly. 

From this point we had two options: 
1) Retry on http call forever until success 
2) Pass message batch and manage offset commits and seeks in our code

I think Option 1) could work, but it wasn't quite straightforward to implement unit test for it to prove it works and test it regressively. Concept of retrying forever on http call does not sound very natural to me though. Code might also not retry on RuntimeException thrown from anywhere.

**Working workaround:**
For now we have implemented Option 2) which commits offset after each success. When error happens we seek back to current message offset position and break loop so kafka consumer will execute next poll starting from last failed message. Code structure looks like below:
`
    @Blocking
    @Topic("${application.kafka.altrefconsumer.topic}")
    public void receive(List<String> invoicesInList, Consumer kafkaConsumer, List<ConsumerRecord<byte[], String>> records) {
        for (ConsumerRecord<byte[], String> record : records) {
            long offset = record.offset();
            int partition = record.partition();
            String topic = record.topic();
            try {
                // 1. process message
                // 2. commitPosition
            } catch (Throwable throwable) {
                kafkaConsumer.seek(new TopicPartition(topic, partition), offset);
                break;
            }
        }
    }
`


List<String> invoicesInList - our code doesn't need it but we needed to add it so Micronout could find and invoke our listener method in @KafkaListener. 

Solution works as we need, but don't use Micronaut framework really. We are forced to process row batch of ConsumerRecords out of Micronaut.

**Comment by graemerocher** [comment] 2019-06-17 21:17
Would appreciate both of your thoughts on https://github.com/micronaut-projects/micronaut-kafka/pull/43

With this change we break out of the loop and don't commit offsets and you can implement `KafkaListenerExceptionHandler` to seek back on failure to allow for redelivery. See https://github.com/micronaut-projects/micronaut-kafka/pull/43/files#diff-1da6eff70608912e65a0eecb802092eaR71

Would this suffice?

**Comment by kziomek** [comment] 2019-06-17 22:00
LGTM. Should work in my scenario.

**Comment by graemerocher** [comment] 2019-06-18 09:05
Since I think this PR should go into 1.1.x I have created https://github.com/micronaut-projects/micronaut-kafka/pull/45 as a replacement PR

**Closed** 2019-06-18 13:05 UTC
Labels: bug

**Comment by paulolieuthier** [comment] 2019-07-24 19:44
@graemerocher I understand seeking is necessary when processing batches, which is the case for @kziomek (is it? I don't see `batch = true` there). But in the test you linked there is no batching. Why is seeking necessary if you don't commit offsets on exception? In my understanding, simply not committing should be enough. What am I missing?
