### ISSUE TITLE
InstanceAlreadyExists Exception with single kafka producer

### ISSUE THREAD

**Issue by jwimg** [micronaut-projects/micronaut-kafka#706] opened 2023-05-09 12:52 UTC
### Issue description

I know this has been raised before however the answer doesn't necessarily cover what is occurring in this particular instance. We have multiple `@KafkaLister`s each with their own client id and responsibilities, this all functions as intended.

Our app core (represented as `AppCore` uses the **singleton class that depends on the KafkaClient**. My initial assumption was because of a race condition between multiple listeners, however given that the `KafkaClient` implementation is created at compile time (according to docs) I believe this wouldn't be fixed by eager initialisation of the `KafkaClientWrapper`. 

```
@KafkaListener(clientId = "a")
class ListenerA(val appCore: AppCore) ...

@KafkaListener(clientId = "b")
class ListenerB(val appCore: AppCore ...

@KafkaClient(id = "client")
interface MyKafkaClient ...

@Singleton
class KafkaClientWrapper(val kafkaClient: MyKafkaClient) ...

@Singleton
class AppCore(val kafkaClientWrapper: KafkaClientWrapper) ...
```

The classic kafka producer config logs are produced 3 times from the same thread
```
[36m13:11:51.890[0;39m [1;30m[pool-1-thread-4][0;39m [34mINFO [0;39m [35mo.a.k.c.producer.ProducerConfig[0;39m - ProducerConfig values:
	acks = -1
	batch.size = 16384
```
The latter 2 are immediately followed by the error:

```
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=client
	at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1865)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:960)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:895)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:523)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:436)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:292)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:319)
	at io.micronaut.configuration.kafka.DefaultProducerFactory.createProducer(DefaultProducerFactory.java:50)
	at io.micronaut.configuration.kafka.KafkaProducerFactory.getProducer(KafkaProducerFactory.java:114)
	at io.micronaut.configuration.kafka.$KafkaProducerFactory$GetProducer0$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:769)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2352)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2233)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1026)
	at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:1001)
	at io.micronaut.context.BeanContext.createBean(BeanContext.java:180)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.lambda$getProducer$35(KafkaClientIntroductionAdvice.java:704)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.getProducer(KafkaClientIntroductionAdvice.java:490)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.intercept(KafkaClientIntroductionAdvice.java:128)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:92)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at xxxxxxx.KafkaClient$Intercepted.xxxx(Unknown Source)
	at xxxxxxx.KafkaClientWrapper.xxxx(KafkaClientWrapper.kt:49)
	at xxxxxxx.AppCore.xxxx(AppCore.kt:107)
	at xxxxxxx.AppCore$xxxx$1.invokeSuspend(AppCore.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at xxxx.ListenerA.receive(KafkaEventController.kt:36)
	at xxxx.$ListenerA$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:76)
	at io.micronaut.core.bind.DefaultExecutableBinder$1.invoke(DefaultExecutableBinder.java:109)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.processConsumerRecords(KafkaConsumerProcessor.java:531)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.createConsumerThreadPollLoop(KafkaConsumerProcessor.java:473)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$submitConsumerThread$7(KafkaConsumerProcessor.java:425)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:196)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by guillermocalvo** [comment] 2023-09-12 11:25
@jwimg I replicated [the scenario](https://github.com/guillermocalvo/micronaut-kafka-issue-706) and tried to reproduce the problem, but my demo app seems to be working as it should in terms of bean instantiation: only one Kafka producer is created and the app starts running. No `InstanceAlreadyExistsException` is thrown. I can produce/consume events and pass them around from one bean to another.

It's possible that this problem has already been resolved in a recent release, so I'm closing this issue now. Please feel free to reopen if it still doesn't work for you, in which case it would be really helpful if you could point us in the right direction by sharing with us a demo app that exhibits the behavior you described.

**Closed by guillermocalvo** 2023-09-12 11:25 UTC
