### ISSUE TITLE
Unconfigured/unused default kafka stream causes an invalid topology

### ISSUE THREAD

**Issue by drmaas** [micronaut-projects/micronaut-kafka#293] opened 2020-12-03 01:14 UTC
When using only `@Named` streams, micronaut-kafka-streams does not run.

```
19:10:40.966 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.apache.kafka.streams.KafkaStreams] could not be loaded: Error instantiating bean of type [org.apache.kafka.streams.KafkaStreams]: Invalid topology: Topology has no stream threads and no global threads, must subscribe to at least one source topic or global table.
```

Example using micronaut 2.2.0, micronaut-kafka-streams 3.1.0, and kafka-streams 2.6.0: https://github.com/drmaas/micronaut-kafka-issue

See https://github.com/micronaut-projects/micronaut-kafka/issues/196 for reference.

**Comment by mcanalesmayo** [comment] 2021-01-04 04:50
Running into the same issue, we can't disable the Kafka streams health check

**Comment by guillermocalvo** [comment] 2023-08-25 10:43
I've been trying to reproduce this issue with the latest versions of the libraries and the problem seems to be solved at the present time. I can update the source code and the continuous build execution works flawlessly.

There used to be some KAPT bugs related to incremental processing that were corrected in the past. These bugfixes could be related to the problem you reported:

- [KAPT does not support aggregating annotations processors in incremental mode](https://youtrack.jetbrains.com/issue/KT-40493)
- [Kapt incremental processing not working](https://youtrack.jetbrains.com/issue/KT-44989)

Since this issue was opened a long time ago and the problem is solved in current releases, I will close it now. Please feel free to raise a new one if you encounter this issue again.

**Closed by guillermocalvo** 2023-08-25 10:43 UTC
