### ISSUE TITLE
Failed to rebalance when running on docker

### ISSUE THREAD

**Issue by henriquelsmti** [micronaut-projects/micronaut-kafka#139] opened 2020-06-01 13:55 UTC
A have this error when two Instance of stream application running on docker.

`ERROR o.a.k.s.p.internals.StreamThread - stream-thread [rebalancing-erro-kafka-streams-micronaut-c99b5a77-07d7-49ea-929d-63bbdc1f0765-StreamThread-4] Encountered the following unexpected Kafka exception during processing, this usually indicate Streams internal errors:
org.apache.kafka.streams.errors.StreamsException: stream-thread [rebalancing-erro-kafka-streams-micronaut-c99b5a77-07d7-49ea-929d-63bbdc1f0765-StreamThread-4] Failed to rebalance.
        at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:862)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:753)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
Caused by: java.lang.NullPointerException: null
        at org.apache.kafka.streams.processor.internals.StreamTask.<init>(StreamTask.java:186)
        at org.apache.kafka.streams.processor.internals.StreamTask.<init>(StreamTask.java:115)
        at org.apache.kafka.streams.processor.internals.StreamThread$TaskCreator.createTask(StreamThread.java:352)
        at org.apache.kafka.streams.processor.internals.StreamThread$TaskCreator.createTask(StreamThread.java:310)
        at org.apache.kafka.streams.processor.internals.StreamThread$AbstractTaskCreator.createTasks(StreamThread.java:295)
        at org.apache.kafka.streams.processor.internals.TaskManager.addNewActiveTasks(TaskManager.java:160)
        at org.apache.kafka.streams.processor.internals.TaskManager.createTasks(TaskManager.java:120)
        at org.apache.kafka.streams.processor.internals.StreamsRebalanceListener.onPartitionsAssigned(StreamsRebalanceListener.java:77)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.invokePartitionsAssigned(ConsumerCoordinator.java:278)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:419)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:439)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:358)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:490)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1275)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1241)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:853)
        ... 3 common frames omitted`

this error always happens in the second instance that is started

I have an exemple In this repository : https://github.com/henriquelsmti/rebalancing-erro-kafka-streams-micronaut

this problem does not happen when I run two instances outside the docker

**Comment by Geeman201** [comment] 2020-09-08 15:31
I hit exactly this issue too!

After much digging I found that it's caused by kafka thinking "the stream" has changed when you do a rolling deploy. 

**Why does the stream change? and why does it matter?**
Lets start with second question there.. It matters when you have a "stateful" stream. Each stream is created with an `application.id` that application id gets [used by a lot of things](https://docs.confluent.io/current/streams/developer-guide/config-streams.html#application-id).. including the name of your `state store` topics. At first I was confused by this but it does make sense.. If you deploy a new version of your stream which filled the `state store` differently, your current state stores would be invalid and not work for your new application code (you could have added a new field for example). So it needs to be re-populated - to do this **you change the `application.id`** or use the `stream reset tool`. 

With the error you see (and I saw) *it is correctly recognising that the stream has changed*. Why does this stream change? 

Well it's all around the `ConfiguredStreamBuilder`. In your example you use the same `ConfiguredStreamBuilder` multiple times.. 
```java 
    @Inject
    @Singleton
    @Named(TopicosConstants.PORTAL_GRUPO_CLIENTES)
    KStream<GenericRecord, GenericRecord> grupoClientesStream(
            @Named("key-serde")  GenericAvroSerde genericKeyAvroDeserializer,
            @Named("value-serde") GenericAvroSerde genericValueAvroDeserializer,
            final ConfiguredStreamBuilder builder
    ) {
        return builder.stream(TopicosConstants.PORTAL_GRUPO_CLIENTES, Consumed.with(genericKeyAvroDeserializer, genericValueAvroDeserializer))
    }

    @Inject
    @Singleton
    @Named(TopicosConstants.PORTAL_GRUPO_OPERADORAS)
    KStream<GenericRecord, GenericRecord> grupoOperadorasStream(
            @Named("key-serde")  GenericAvroSerde genericKeyAvroDeserializer,
            @Named("value-serde") GenericAvroSerde genericValueAvroDeserializer,
            final ConfiguredStreamBuilder builder
    ) {
        return builder.stream(TopicosConstants.PORTAL_GRUPO_OPERADORAS, Consumed.with(genericKeyAvroDeserializer, genericValueAvroDeserializer))
    }
```

Which actually means each "stream" (heavily in inverted commas there) is being appended to the same `ConfiguredStreamBuilder`. This is a problem because when the "stream"s get registered by `micronaut-kafka`. The `ConfiguredStreamBuilder` is built into a topology and then ran as a *single stream* with *multiple sub topologies*..

This sounds confusing but basically means that your micronaut application is actually running a single stream rather than what you expect which is multiple. The topology of the single running stream is something like this (this is a noddy example)..
```
Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000001 (topics: [in-1])
      --> KSTREAM-SINK-0000000002
    Sink: KSTREAM-SINK-0000000002 (topic: out-1)
      <-- KSTREAM-SOURCE-0000000001

  Sub-topology: 1
    Source: KSTREAM-SOURCE-0000000004 (topics: [in-2])
      --> KSTREAM-SINK-0000000005
    Sink: KSTREAM-SINK-0000000005 (topic: out-2)
      <-- KSTREAM-SOURCE-0000000004
```

So why does this cause a problem at rollout? Well the order which your "streams registration methods" are called can change so the next time your application starts the order of the `sub topologies` may differ. The stream rightly recognises that it is totally different and is registered with the same `application.id` so won't allow it until all previous versions are shut down. 
```
Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000001 (topics: [in-2]) <--- Note this is "in-2" rather than "in-1"
      --> KSTREAM-SINK-0000000002
    Sink: KSTREAM-SINK-0000000002 (topic: out-2)
      <-- KSTREAM-SOURCE-0000000001

  Sub-topology: 1
    Source: KSTREAM-SOURCE-0000000004 (topics: [in-1])
      --> KSTREAM-SINK-0000000005
    Sink: KSTREAM-SINK-0000000005 (topic: out-1)
      <-- KSTREAM-SOURCE-0000000004
```

The way to fix this is to set each `ConfiguredStreamBuilder` to be a `@Named` bean so each one results in a different stream being created. 

```java
    @Inject
    @Singleton
    @Named(TopicosConstants.PORTAL_GRUPO_OPERADORAS)
    KStream<GenericRecord, GenericRecord> grupoOperadorasStream(
            @Named("key-serde")  GenericAvroSerde genericKeyAvroDeserializer,
            @Named("value-serde") GenericAvroSerde genericValueAvroDeserializer,
            @Named("portal-public-grupo-operadoras")final ConfiguredStreamBuilder builder
    )
```

For each `ConfiguredStreamBuilder` you then need to create an entry in the `application.yml`
```yml
kafka:
  streams:
    portal-public-grupo-operadoras: 
      application.id: ${micronaut.application.name}-portal-public-grupo-operadoras
#  extra config
```

After I did the above for all my `ConfiguredStreamBuilder`s, I hit a slightly different problem at startup:
```
java.lang.IllegalStateException: Consumer is not subscribed to any topics or assigned any partitions
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1228)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:853)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:753)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
```
After digging into that one.. One of the `ConfiguredStreamBuilder`s must be called `default` as the `default` `ConfiguredStreamBuilder` is always created. 

For the above example
```java
    @Inject
    @Singleton
    @Named(TopicosConstants.PORTAL_GRUPO_CLIENTES)
    KStream<GenericRecord, GenericRecord> grupoClientesStream(
            @Named("key-serde")  GenericAvroSerde genericKeyAvroDeserializer,
            @Named("value-serde") GenericAvroSerde genericValueAvroDeserializer,
            @Named("default") final ConfiguredStreamBuilder builder
    ) {
        return builder.stream(TopicosConstants.PORTAL_GRUPO_CLIENTES, Consumed.with(genericKeyAvroDeserializer, genericValueAvroDeserializer))
    }

    @Inject
    @Singleton
    @Named(TopicosConstants.PORTAL_GRUPO_OPERADORAS)
    KStream<GenericRecord, GenericRecord> grupoOperadorasStream(
            @Named("key-serde")  GenericAvroSerde genericKeyAvroDeserializer,
            @Named("value-serde") GenericAvroSerde genericValueAvroDeserializer,
            @Named("portal-public-grupo-operadoras")final ConfiguredStreamBuilder builder
    ) {
        return builder.stream(TopicosConstants.PORTAL_GRUPO_OPERADORAS, Consumed.with(genericKeyAvroDeserializer, genericValueAvroDeserializer))
    }
```

```yml
kafka:
  streams:
    default: 
      application.id: ${micronaut.application.name}-portal-public-cliente-stream
    portal-public-grupo-operadoras:
      application.id: ${micronaut.application.name}-portal-public-grupo-operadoras
```

Hope this helps,
James

**Comment by alvarosanchez** [comment] 2020-09-10 08:51
Closing as per @geemanjs's wonderful explanation.

**Closed by alvarosanchez** 2020-09-10 08:51 UTC
Labels: closed: notabug
