### ISSUE TITLE
micronaut-kafka-streams BeanInstantiationException - KAPT

### ISSUE THREAD

**Issue by tomasfabian** [micronaut-projects/micronaut-kafka#311] opened 2021-01-26 09:29 UTC
**Steps to Reproduce:**
I created a sample project with the following command:
```
mn create-app my-kafka-streams2 --features kafka-streams --lang=kotlin --build gradle
```
At the beginning it worked. Everytime I did a change in the @KafkaListener it stopped working with the following error:

**Output:**
```
10:11:52.228 [main] INFO  o.apache.kafka.streams.KafkaStreams - stream-client [my-kafka-streams2-263ecdbd-186e-4762-bc2e-82d43f5fc609] Kafka Streams version: 2.7.0
10:11:52.228 [main] INFO  o.apache.kafka.streams.KafkaStreams - stream-client [my-kafka-streams2-263ecdbd-186e-4762-bc2e-82d43f5fc609] Kafka Streams commit ID: 448719dc99a19793
10:11:52.230 [main] INFO  o.apache.kafka.streams.KafkaStreams - stream-client [my-kafka-streams2-263ecdbd-186e-4762-bc2e-82d43f5fc609] Overriding number of StreamThreads to zero for global-only topology
10:11:52.230 [main] ERROR o.apache.kafka.streams.KafkaStreams - stream-client [my-kafka-streams2-263ecdbd-186e-4762-bc2e-82d43f5fc609] Topology with no input topics will create no stream threads and no global thread.
10:11:52.233 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.apache.kafka.streams.KafkaStreams] could not be loaded: Error instantiating bean of type [org.apache.kafka.streams.KafkaStreams]: Invalid topology: Topology has no stream threads and no global threads, must subscribe to at least one source topic or global table.
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.apache.kafka.streams.KafkaStreams] could not be loaded: Error instantiating bean of type [org.apache.kafka.streams.KafkaStreams]: Invalid topology: Topology has no stream threads and no global threads, must subscribe to at least one source topic or global table.
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1549)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2812)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at my.kafka.streams2.ApplicationKt.main(Application.kt:15)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.apache.kafka.streams.KafkaStreams]: Invalid topology: Topology has no stream threads and no global threads, must subscribe to at least one source topic or global table.
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1927)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2679)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2665)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2204)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1543)
	... 6 common frames omitted
Caused by: org.apache.kafka.streams.errors.TopologyException: Invalid topology: Topology has no stream threads and no global threads, must subscribe to at least one source topic or global table.
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:729)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:653)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:563)
	at io.micronaut.configuration.kafka.streams.KafkaStreamsFactory.kafkaStreams(KafkaStreamsFactory.java:92)
	at io.micronaut.configuration.kafka.streams.$KafkaStreamsFactory$KafkaStreams1Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:148)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	... 10 common frames omitted

Process finished with exit code 1
```

**Environment:**
Android Studio 4.1.2
Gradle 6.7

I tried to increase the version of packages etc. in the following manner:
```gradle
//gradle.properties
micronautVersion=2.3.0
kotlinVersion=1.4.21

//build.gradle
plugins {
    id("org.jetbrains.kotlin.jvm") version "${kotlinVersion}"
    id("org.jetbrains.kotlin.kapt") version "${kotlinVersion}"
    id("org.jetbrains.kotlin.plugin.allopen") version "${kotlinVersion}"
    id("com.github.johnrengelman.shadow") version "6.1.0"
    id("io.micronaut.application") version "1.3.2"
}

version = "0.1"
group = "my.kafka.streams2"

repositories {
    mavenCentral()
    jcenter()
}

micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)//false didn't help
        annotations("my.kafka.streams2.*")
    }
}

dependencies {
    implementation("io.micronaut:micronaut-validation")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
    implementation("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut:micronaut-runtime")
    implementation("javax.annotation:javax.annotation-api")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut.kafka:micronaut-kafka")
    implementation("io.micronaut.kafka:micronaut-kafka-streams")
    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")
}

application {
    mainClass.set("my.kafka.streams2.ApplicationKt")
}

java {
    sourceCompatibility = JavaVersion.toVersion("11")
}

compileKotlin {
    kotlinOptions.jvmTarget = "11"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "11"
}
```
**Workaround:**
I found out that when I changed something in the build.gradle file it started to work after sync.

Later I decided to RTM of kapt and tried to turn off the incremental annotation processing and it helped:
```gradle
kapt.incremental.apt=false
```

Is this an issue with KAPT or Micronaut (micronaut-kafka/micronaut-kafka-streams)? 

I found a similar [issue here](https://github.com/micronaut-projects/micronaut-kafka/issues/293)

Thank you.

**Comment by guillermocalvo** [comment] 2023-08-25 10:40
I've been trying to reproduce this issue with the latest versions of the libraries and the problem seems to be solved at the present time. I can update the source code and the continuous build execution works flawlessly.

There used to be some KAPT bugs related to incremental processing that were corrected in the past. These bugfixes could be related to the problem you reported:

- [KAPT does not support aggregating annotations processors in incremental mode](https://youtrack.jetbrains.com/issue/KT-40493)
- [Kapt incremental processing not working](https://youtrack.jetbrains.com/issue/KT-44989)

Since this issue was opened a long time ago and the problem is solved in current releases, I will close it now. Please feel free to raise a new one if you encounter this issue again.

**Closed by guillermocalvo** 2023-08-25 10:40 UTC
