### ISSUE TITLE
General configuration issues with micronaut-kafka

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-kafka#320] opened 2021-02-09 15:29 UTC
### Task List

- [X] Steps to reproduce provided
- [-] Stacktrace (if present) provided
- [-] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a micronaut project using micronaut Kafka
2. Configure parts of the configuration in application.yml (i.E. kafka.producers.default.compression.type: gzip)
3. Try to configure a different part with an environment variable (i.E. KAFKA_BOOTSTRAP_SERVERS)

### Expected Behaviour

Configuration values are combined like we are used to from micronaut

### Actual Behaviour

As soon as any property kafka.* is configured within any .yml file that is loaded, every KAFKA_* environment variable gets ignored.

### Environment Information

- **Operating System**: Windows
- **Micronaut Version:** From. 2.0.0 to 2.3.1 (different versions same problem)
- **JDK Version:** 8 - 11

**Comment by burtbeckwith** [comment] 2021-03-04 20:18
This is a duplicate of https://github.com/micronaut-projects/micronaut-kafka/issues/179 but that fix hasn't been released yet. We'll be releasing this module this week to be included in next week's Micronaut 2.4 release

**Closed by burtbeckwith** 2021-03-04 20:18 UTC
Labels: priority: high, type: bug

**Comment by ckosmowski** [comment] 2021-11-25 13:01
We are still experiencing this problem. It does not seem to be an exact duplicate of the ticket mentioned by @burtbeckwith. If we i.e. config kafka.bootstrap.servers in yml everything from the enrionment variables is ignored. (Especially interesting for us is KAFKA_PRODUCERS_DEFAULT_*). But these are ignored.

However if we name the environment variables literally kafka.producers.default.* as env variable names it works correctly.
