### ISSUE TITLE
NPE using micronaut with confluent cloud kafka

### ISSUE THREAD

**Issue by danprueitt** [micronaut-projects/micronaut-kafka#201] opened 2020-07-29 10:30 UTC
When using Micronaut Kafka with Confluent cloud Kafka platform a NPE is produced when Micronaut tries to get the `REPLICATION_PROPERTY`.
```
              ConfigEntry ce = config.get(REPLICATION_PROPERTY);
                int replicationFactor = Integer.parseInt(ce.value());
```

This is because the confluent Kafka cloud platform doesn't use/expose these values. 

Stacktrace:
```
 Jul 29 10:52:01 4ea39db8273b java.lang.NullPointerException null
 Jul 29 10:52:01 4ea39db8273b at io.micronaut.configuration.kafka.health.KafkaHealthIndicator.lambda$null$2(KafkaHealthIndicator.java:87)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onNext(FlowableSwitchMap.java:113)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFromFuture.subscribeActual(FlowableFromFuture.java:53)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14918)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14918)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14865)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onNext(FlowableSwitchMap.java:129)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFromFuture.subscribeActual(FlowableFromFuture.java:53)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14918)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14918)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableOnErrorReturn.subscribeActual(FlowableOnErrorReturn.java:33)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14918)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14865)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:236)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14918)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14918)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:37)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Flowable.subscribe(Flowable.java:14918)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
 Jul 29 10:52:01 4ea39db8273b at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 Jul 29 10:52:01 4ea39db8273b at io.micronaut.management.health.monitor.HealthMonitorTask.monitor(HealthMonitorTask.java:98)
 Jul 29 10:52:01 4ea39db8273b at io.micronaut.management.health.monitor.$HealthMonitorTaskDefinition$$exec1.invokeInternal(Unknown Source)
 Jul 29 10:52:01 4ea39db8273b at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
 Jul 29 10:52:01 4ea39db8273b at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:76)
 Jul 29 10:52:01 4ea39db8273b at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:125)
 Jul 29 10:52:01 4ea39db8273b at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 Jul 29 10:52:01 4ea39db8273b at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
 Jul 29 10:52:01 4ea39db8273b at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
 Jul 29 10:52:01 4ea39db8273b at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 Jul 29 10:52:01 4ea39db8273b at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 Jul 29 10:52:01 4ea39db8273b at java.base/java.lang.Thread.run(Thread.java:830)
```

### Task List

- [ x ] Steps to reproduce provided
- [ x ] Stacktrace (if present) provided
- [  ] Example that reproduces the problem uploaded to Github
- [ x ] Full description of the issue provided (see below)

### Steps to Reproduce

Use confluent cloud platform with Micronaut Kafka or simulate the server not having these config values.

### Expected Behaviour

If the values are not set, use a default.

### Actual Behaviour

A npe is thrown

### Environment Information

- **Operating System**: Ubuntu
- **Micronaut Version:** 1.3.6
- **JDK Version:** VERSION_1_8

**Comment by graemerocher** [comment] 2020-07-29 11:15
Micronaut 1.4.0 doesn't exist, can you try upgrade to a newer version? Seems to be a duplicate of https://github.com/micronaut-projects/micronaut-kafka/issues/11

**Comment by danprueitt** [comment] 2020-07-29 16:41
Yeah i must have looked at a version of something else. We use Micronaut 1.3.6. I can suggest upgrading to the team if you think that will help?

**Comment by graemerocher** [comment] 2020-07-29 16:43
yes upgrading will help

**Comment by omarsahl** [comment] 2020-12-18 18:43
Seems like Confluent clusters only have the `default.replication.factor` property instead of the `offsets.topic.replication.factor` property which I believe is the cause of the NPE.
https://docs.confluent.io/cloud/current/clusters/broker-config.html#cloud-broker-config
Is there any workaround for this?

**Comment by Nanabell** [comment] 2021-02-19 09:06
This is still a problem on the newest version of Micronaut(2.3.2) & mn-kafka(3.1.0). 
As described above `offsets.topic.replication.factor` is not available but `default.replication.factor` is. 

Disabling the KafkaHealthIndicator seems to be the simplest solution when working with Confluent Cloud

**Comment by mitchjust-finocomp** [comment] 2021-02-26 02:26
@graemerocher I can confirm that this issue is still present in Micronaut 2.3.3

setting
```
kafka.health.enabled: false
```

resolves the issue.

**Closed** 2021-02-26 11:00 UTC
Labels: status: awaiting feedback
